apiVersion: batch/v1
kind: Job
metadata:
  name: wait
spec:
  completions: 3
  template:
    metadata:
      name: wait
    spec:
      containers:
      - name: wait
        image: ubuntu
        command: ["sleep",  "15"]
      restartPolicy: Never