apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: customnginx
  name: customnginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: customnginx
  type: LoadBalancer
status:
  loadBalancer: {}
