### Taken directly from https: 

: 
apiVersion: The chart API version (required)
name: 
version: 
kubeVersion: 
description: 
type: 
keywords: 
  - A list of keywords about this project (optional)
: 
home: 
sources: 
  - A list of URLs to source code for this project (optional)
: 
dependencies: 
  - name: 
    version: 
    repository: 
    condition: 
    tags: 
      - Tags can be used to group charts for enabling/disabling together
: 
    import-values: 
      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
: 
    alias: 
maintainers: 
  - name: 
    email: 
    url: 
icon: 
appVersion: 
deprecated: 
annotations: 
  example: 
