apiVersion: v1
kind: PersistentVolume
metadata: 
  name: 
spec: 
  capacity: 
    storage: 
  accessModes: 
    - ReadWriteOnce
: 
    - ReadWriteMany
: 
  persistentVolumeReclaimPolicy: 
  nfs: 
    server: 
    path: 
