apiVersion: apps/v1 #version of the API to use
kind: Deployment #What kind of object we're deploying
metadata: 
  name: 
  labels: 
    app: 
spec: 
  replicas: 
  selector: 
    matchLabels: 
      app: 
  template: 
    metadata: 
      labels: 
        app: 
    spec: 
      containers: 
      - name: 
        image: 
        ports: 
        - containerPort: 
---
: 
apiVersion: v1 #version of the API to use
kind: Service #What kind of object we're deploying
metadata: 
  name: 
spec: 
  type: 
  ports: 
  - name: 
    port: 
    targetPort: 
    nodePort: 
    protocol: 
  selector: 
    app: 
