apiVersion: v1 #version of the API to use
kind: Pod #What kind of object we're deploying
metadata: 
  name: 
  labels: 
    env: 
spec: 
  containers: 
  - name: 
    image: 
    imagePullPolicy: 
  nodeSelector: 
    mynode: 
